# Wraith Device Transfer Makefile
# Auto-generated by WraithImageBridge
# Device: iPad1,1 (A4)
# Protocol: irecovery
# Flash Mode: direct_nand

DEVICE_ID = iPad1,1
CHIP = A4
NAND_BASE = 0x09000000
IRECOVERY = irecovery
CHARGFAST = N:/ROMLOADDER/chargfast\ via\ usb
PYTHON_BRIDGE = python3 wraith_image_bridge.py
NODEPACK_DIR = .

# Component definitions (populated by wraith_image_bridge.py)
LLB_SOURCE = extracted/Firmware/all_flash/all_flash.k48ap.production/LLB.k48ap.RELEASE.img3
LLB_OFFSET = 0x0
LLB_SIZE = 0x100000

IBOOT_SOURCE = extracted/Firmware/all_flash/all_flash.k48ap.production/iBoot.k48ap.RELEASE.img3
IBOOT_OFFSET = 0x100000
IBOOT_SIZE = 0x100000

DEVICETREE_SOURCE = extracted/Firmware/all_flash/all_flash.k48ap.production/DeviceTree.k48ap.img3
DEVICETREE_OFFSET = 0x200000
DEVICETREE_SIZE = 0x100000

KERNELCACHE_SOURCE = extracted/kernelcache.release.k48
KERNELCACHE_OFFSET = 0x600000
KERNELCACHE_SIZE = 0x1000000

ROOTFS_SOURCE = extracted/038-1421-004.dmg
ROOTFS_OFFSET = 0x1600000
ROOTFS_SIZE = 0x20000000

# Image bridge paths
IMAGE_BRIDGE = wraith_image_bridge.py
MIRROR_MANAGER = wraith_mirror_manager.js
FLASH_MODE_JS = wraith_flash.js
CENTRAL_ORCHESTRATOR = central_orchestrator.js
CONTROL_CENTER = CONTROL_CENTER.js

# Wraith directories
WRATH_DIR = wraithps4-serv-backup-performance\ booster
IOSROM_DIR = IOsrom

.PHONY: all help detect status prepare extract flash verify clean reboot \
        wraith-flash wraith-mirror wraith-bridge makefile transfer update \
        ipsw-extract nand-flash device-sync package-update

all: detect prepare

help:
	@echo "Wraith Device Transfer Makefile"
	@echo "================================"
	@echo ""
	@echo "Targets:"
	@echo "  detect        - Detect connected device"
	@echo "  status        - Show device and mirror status"
	@echo "  prepare       - Prepare directories and environment"
	@echo "  extract       - Extract IPSW components"
	@echo "  flash         - Flash all components to NAND"
	@echo "  verify        - Verify NAND integrity"
	@echo "  clean         - Clean extracted files"
	@echo "  reboot        - Reboot device"
	@echo ""
	@echo "Wraith Integration:"
	@echo "  wraith-flash  - Run wraith flash mode"
	@echo "  wraith-mirror - Sync device library mirror"
	@echo "  wraith-bridge - Initialize wraith image bridge"
	@echo "  makefile      - Generate this Makefile"
	@echo "  transfer      - Full transfer pipeline"
	@echo ""
	@echo "Package Management:"
	@echo "  update        - Apply package updates via mirror"
	@echo "  ipsw-extract  - Extract IPSW to mirror"
	@echo "  nand-flash    - Flash extracted components to NAND"
	@echo "  device-sync   - Sync device library to mirror"
	@echo "  package-update - Update specific package on device"

detect:
	@echo "[+] Detecting device via RJ45/USB..."
	@$(IRECOVERY) -c getenv | head -5 || echo "[!] Device not detected"
	@echo "[+] Device detection complete"

status:
	@echo "[+] Wraith System Status"
	@echo "  Device connected: $(shell $(IRECOVERY) -c getenv > /dev/null 2>&1 && echo YES || echo NO)"
	@echo "  Mirror directory: $(shell test -d library_mirror && echo EXISTS || echo MISSING)"
	@echo "  Wraith directory: $(shell test -d '$(WRATH_DIR)' && echo EXISTS || echo MISSING)"
	@echo "  IOsrom directory: $(shell test -d '$(IOSROM_DIR)' && echo EXISTS || echo MISSING)"
	@echo "  Flash mode: ENABLED"
	@echo "  RJ45 active: CHECKING..."

prepare:
	@echo "[+] Preparing directories..."
	@mkdir -p library_mirror/images library_mirror/packages library_mirror/nand
	@mkdir -p library_mirror/boot library_mirror/system library_mirror/frameworks
	@mkdir -p extracted
	@echo "[+] Directories prepared"

extract:
	@echo "[+] Extracting IPSW components..."
	@$(PYTHON_BRIDGE) . --extract *.ipsw
	@echo "[+] Extraction complete"

flash: prepare extract
	@echo "[+] Flashing components to NAND..."
	@$(PYTHON_BRIDGE) . --flash-nand
	@echo "[+] Flash complete"

verify:
	@echo "[+] Verifying NAND integrity..."
	@$(IRECOVERY) -c getenv | grep boot-partition
	@echo "[+] Verification complete"

clean:
	@echo "[+] Cleaning extracted files..."
	@rm -rf extracted/*
	@echo "[+] Clean complete"

reboot:
	@echo "[+] Rebooting device..."
	@$(IRECOVERY) -c reboot
	@echo "[+] Reboot command sent"

# Wraith integration targets
wraith-flash:
	@echo "[+] Running wraith flash mode..."
	@node $(FLASH_MODE_JS) . flash
	@echo "[+] Wraith flash complete"

wraith-mirror:
	@echo "[+] Syncing device library mirror..."
	@node $(MIRROR_MANAGER) . --mirror
	@echo "[+] Mirror sync complete"

wraith-bridge:
	@echo "[+] Initializing wraith image bridge..."
	@$(PYTHON_BRIDGE) . --mirror
	@echo "[+] Bridge initialized"

makefile:
	@echo "[+] Generating transfer Makefile..."
	@$(PYTHON_BRIDGE) . --makefile
	@echo "[+] Makefile generated: wraith_transfer.mk"

transfer: detect prepare extract flash verify
	@echo "[+] Full transfer pipeline complete"

# Package management targets
update:
	@echo "[+] Applying package updates via mirror..."
	@node $(MIRROR_MANAGER) . --update
	@echo "[+] Updates applied"

ipsw-extract:
	@echo "[+] Extracting IPSW to mirror..."
	@$(PYTHON_BRIDGE) . --extract $(IPS)
	@echo "[+] IPSW extracted to mirror"

nand-flash:
	@echo "[+] Flashing extracted components to NAND..."
	@$(PYTHON_BRIDGE) . --flash-nand
	@echo "[+] NAND flash complete"

device-sync:
	@echo "[+] Syncing device library to mirror..."
	@$(PYTHON_BRIDGE) . --mirror
	@echo "[+] Device sync complete"

package-update:
	@echo "[+] Updating package on device..."
	@node $(MIRROR_MANAGER) . --package-update $(PKG) $(VER) $(LANG)
	@echo "[+] Package updated"

# Central orchestrator integration
orchestrator:
	@echo "[+] Running central orchestrator..."
	@node $(CENTRAL_ORCHESTRATOR) . flash
	@echo "[+] Orchestrator complete"

control-center:
	@echo "[+] Running control center..."
	@node $(CONTROL_CENTER) flash
	@echo "[+] Control center complete"

# IOsrom integration targets
iosrom-nand:
	@echo "[+] Running IOsrom NAND flasher..."
	@cd $(IOSROM_DIR) && python3 direct_nand_flasher.py
	@echo "[+] IOsrom NAND flash complete"

iosrom-final:
	@echo "[+] Running IOsrom FINAL_NAND_FLASH..."
	@cd $(IOSROM_DIR) && python3 FINAL_NAND_FLASH.py
	@echo "[+] IOsrom final flash complete"

iosrom-write:
	@echo "[+] Running IOsrom WRITE_NAND_DIRECT..."
	@cd $(IOSROM_DIR) && python3 WRITE_NAND_DIRECT.py
	@echo "[+] IOsrom direct write complete"

# Fast targets (flash mode optimized)
fast-flash: detect prepare flash
	@echo "[+] Fast flash complete"

fast-transfer: detect prepare extract flash verify
	@echo "[+] Fast transfer complete"

# Help target
.DEFAULT_GOAL := help
